wandb_version: 1

K:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1725054669
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      3:
      - 16
      4: 3.8.10
      5: 0.12.7
      6: 4.25.1
      8:
      - 5
arch:
  desc: null
  value: resnet18
backbone:
  desc: null
  value: resnet50
batch_size:
  desc: null
  value: 256
data_path:
  desc: null
  value: data
dataset:
  desc: null
  value: SMA
img_size:
  desc: null
  value: 32
input_size:
  desc: null
  value: 224
loss:
  desc: null
  value: simsiam
lr:
  desc: null
  value: 0.05
method:
  desc: null
  value: erm
mode:
  desc: null
  value: classic
momentum:
  desc: null
  value: 0.9
mu:
  desc: null
  value: 0.1
name:
  desc: null
  value: medical-leaf
num_epochs:
  desc: null
  value: 100
pretraining_name:
  desc: null
  value: simsiam1
rr_prob:
  desc: null
  value: 0.5
split_seed:
  desc: null
  value: 4
vf_prob:
  desc: null
  value: 0.5
wandb_project:
  desc: null
  value: SMA_cl_pretrain
weight_decay:
  desc: null
  value: 0.0001
