wandb_version: 1

IR:
  desc: null
  value: 0.1
K:
  desc: null
  value: 2
Ks:
  desc: null
  value:
  - 2
T:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1724246627
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      3:
      - 16
      4: 3.8.10
      5: 0.12.7
      6: 4.25.1
      8:
      - 5
alpha:
  desc: null
  value: 0.5
arch:
  desc: null
  value: resnet18
batch_size:
  desc: null
  value: 16
cl_mode:
  desc: null
  value: bce+supcon
config_name:
  desc: null
  value: config_local.yaml
data_path:
  desc: null
  value: data
dataset:
  desc: null
  value: SMA
eta:
  desc: null
  value: 0.1
eval_every_n_epochs:
  desc: null
  value: 3
group:
  desc: null
  value: K=2_erm
group_best:
  desc: null
  value: medical-leaf_K=2_erm_mu=0.1_seed=0
hparams_seed:
  desc: null
  value: 0
img_size:
  desc: null
  value: 64
init_seed:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.0004974556006241091
max_time:
  desc: null
  value: 4320
method:
  desc: null
  value: erm
methods:
  desc: null
  value:
  - erm
mode:
  desc: null
  value: classic
mu:
  desc: null
  value: 0.1
mus:
  desc: null
  value:
  - 0.1
n_HBO_runs:
  desc: null
  value: 3
n_eval_init_seed:
  desc: null
  value: 1
n_gpus:
  desc: null
  value: 1
name:
  desc: null
  value: medical-leaf
names:
  desc: null
  value:
  - medical-leaf
new_reset:
  desc: null
  value: false
num_epochs:
  desc: null
  value: 10
num_hparams_seeds:
  desc: null
  value: 20
output_dir:
  desc: null
  value: outputs
scheduler:
  desc: null
  value: false
selector:
  desc: null
  value: mean_grp_acc_va
slurm_output_dir:
  desc: null
  value: slurm_outputs
slurm_partition:
  desc: null
  value: null
split_seed:
  desc: null
  value: 0
split_seeds:
  desc: null
  value:
  - 0
up:
  desc: null
  value: 20
wandb_project:
  desc: null
  value: SMA_debug
weight_decay:
  desc: null
  value: 0.001
