wandb_project: SMA_cl_pretrain
pretraining_suffix: ''
data_path: 'data'
dataset: 'SMA'
loss: 'moco'  # Options: simsiam, moco, swav
input_size: 32
vf_prob: 0.5  # Vertical flip probability
rr_prob: 0.5  # Random rotation probability
batch_size: 8
num_epochs: 11
lr: 0.05
momentum: 0.9
weight_decay: 1e-4
method: 'erm'
arch: 'resnet50'

SMA:
  mode: 'classic'
  K: 2
  mu: 0.1
  name: 'medical-leaf'
  split_seed: 0
  img_size: 224