wandb_project: SMA_cl_pretrain
pretraining_suffix: ''
data_path: 'data'
dataset: 'SMA'
loss: 'moco'  # Options: simsiam, moco, swav
backbone: 'resnet50'
input_size: 224
vf_prob: 0.5  # Vertical flip probability
rr_prob: 0.5  # Random rotation probability
batch_size: 64
num_epochs: 200
lr: 0.05
momentum: 0.9
weight_decay: 1e-4
method: 'erm'
arch: 'resnet50'

SMA:
  mode: 'classic'
  K: 16
  mu: 0.2
  name: 'dogs'
  split_seed: 0
  img_size: 224