wandb_project: 'PLT'
output_dir: 'outputs'
slurm_output_dir: 'slurm_outputs'
data_path: 'data'
slurm_partition: null #Pas None ?
max_time: 4320  # 3 * 24 * 60
num_hparams_seeds: 20
num_init_seeds: 5
selector: 'min_acc_va'

#Sweep
#['erm','jtt', 'suby', 'subg', 'rwy', 'rwg', 'dro']
method:  #  'jtt', 'suby' 'subg', 'rwy', 'rwg', 'dro'
dataset: 'SMA'
init_seed: 0
hparams_seed: 0
eval_every_n_epochs: 1
arch: "resnet50"
# Hyperparameters for all methods

num_epochs: 25
batch_size: 16
eta: 0.1
lr: 1e-3
weight_decay: 1e-3
up: 20 #[4, 5, 6, 20, 50, 100]
T: 3 #[40, 50, 60]
scheduler: False



# Specific hyperparameters for to create SMA dataset
SMA:
  name: 'plt-net'
  split_seed: 0
  K: 2
  mu: 0.1
  img_size: 256


