wandb_project: 'AWA resnset 18 vs 50'
output_dir: 'outputs'
slurm_output_dir: 'slurm_outputs'
data_path: 'data'
slurm_partition: null #Pas None ?
max_time: 4320  # 3 * 24 * 60
num_hparams_seeds: 20
num_init_seeds: 5
selector: 'min_acc_va'

#Sweep
#['erm','jtt', 'suby', 'subg', 'rwy', 'rwg', 'dro']
method: ['erm','jtt']   #  'jtt', 'suby' 'subg', 'rwy', 'rwg', 'dro'
dataset: ['SMA']
init_seed: [0]
hparams_seed: [0]
eval_every_n_epochs: 1
arch: "resnet50"
# Hyperparameters for all methods

num_epochs: [20,40,60]
batch_size: [16]
lr: [1e-3, 1e-4]
weight_decay: [1e-3]
up: [5] #[4, 5, 6, 20, 50, 100]
T: [3] #[40, 50, 60]
scheduler: [False]



# Specific hyperparameters for to create SMA dataset
SMA:
  name: 'AWA'
  split_seed: [0,1,2]
  K: [2,4,8]
  mu: 0.05
  img_size: 256



#
#wandb_project: 'AWA K=2_4_8 big '
#output_dir: 'outputs'
#slurm_output_dir: 'slurm_outputs'
#data_path: 'data'
#slurm_partition: null #Pas None ?
#max_time: 4320  # 3 * 24 * 60
#num_hparams_seeds: 20
#num_init_seeds: 5
#selector: 'min_acc_va'
#
##Sweep
##['erm','jtt', 'suby', 'subg', 'rwy', 'rwg', 'dro']
#method: ['erm','jtt', 'suby' 'subg', 'rwy', 'rwg', 'dro']   #  'jtt', 'suby' 'subg', 'rwy', 'rwg', 'dro'
#dataset: ['SMA']
#init_seed: [0]
#hparams_seed: [0]
#eval_every_n_epochs: 1
#arch: "resnet18"
## Hyperparameters for all methods
#
#num_epochs: [20,40,60]
#batch_size: [16]
#eta: 0.1
#lr: [1e-3, 1e-4, 1e-5, 1e-6]
#weight_decay: [1e-3]
#up: [20] #[4, 5, 6, 20, 50, 100]
#T: [3] #[40, 50, 60]
#scheduler: [False]
#
#
#
## Specific hyperparameters for to create SMA dataset
#SMA:
#  name: 'AWA'
#  split_seed: [0,1,2,3,4]
#  K: [2,4,8]
#  mu: 0.05
#  img_size: 256
#

