wandb_project: SMA_cl
output_dir: 'outputs'
slurm_output_dir: 'slurm_outputs'
data_path: 'data'
slurm_partition: null #Pas None ?
max_time: 4320  # 3 * 24 * 60
num_hparams_seeds: 20
#num_init_seeds: 5
selector: 'worst_acc_va' # mean_acc_va

#Sweep
#['erm','jtt', 'suby', 'subg', 'rwy', 'rwg', 'dro']
method:  #  'jtt', 'suby' 'subg', 'rwy', 'rwg', 'dro'
dataset: 'SMA'
init_seed: 0
hparams_seed: 0
eval_every_n_epochs: 3
arch: "resnet18"
# Hyperparameters for all methods


n_HBO_runs: 3
n_eval_init_seed: 1

num_epochs: 17
batch_size: 16
eta: 0.1
lr: 1e-3
weight_decay: 1e-3
up: 20 #[4, 5, 6, 20, 50, 100]
T: 3
scheduler: False
new_reset: False


cl_modes: ['bce','bce+supcon'] # "bce+supcon"
alphas: [0,0.05,.1,.2,.5,.9,.95,1] #alpha * supcon + (1-alpha) bce

# Specific hyperparameters for to create SMA dataset
SMA:
  mode: 'classic'
  img_size: 224
  split_seeds: [0]
  names:  ['dogs'] #plt-net ins2 medical-leaf texture-dtd
  Ks: [4]
  mus: [0.1]
  methods: ['erm']





