wandb_project: 'SMA_Imbalance_16x16'
output_dir: 'outputs'
slurm_output_dir: 'slurm_outputs'
data_path: 'data'
slurm_partition: null #Pas None ?
max_time: 4320  # 3 * 24 * 60
num_hparams_seeds: 20
num_init_seeds: 5
selector: 'min_acc_va'

#Sweep
#['erm','jtt', 'suby', 'subg', 'rwy', 'rwg', 'dro']
method: ['erm','jtt', 'suby', 'subg', 'rwy', 'rwg', 'dro']
dataset: ['SMA']
init_seed: [0]
hparams_seed: [0]
eval_every_n_epochs: 1
arch: "resnet18"
# Hyperparameters for all methods

num_epochs: [20]
batch_size: 16
eta: 0.1
lr: [1e-4]
weight_decay: [1e-4]
up: [4] #[4, 5, 6, 20, 50, 100]
T: 40 #[40, 50, 60]



# Specific hyperparameters for to create SMA dataset
SMA:
  name: 'AWA'
  split_seed: 0
  K: 4
  mu: 0.05
  img_size: 256